import{a as S,S as E,i}from"./assets/vendor-DfRjFiQT.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))c(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const n of o.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&c(n)}).observe(document,{childList:!0,subtree:!0});function a(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function c(e){if(e.ep)return;e.ep=!0;const o=a(e);fetch(e.href,o)}})();const P="52827134-53a8d98a66d236597fa2c26fa",R=15;async function m(r,t){return(await S.get("https://pixabay.com/api/",{params:{key:P,q:r,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:R,page:t}})).data}const p=document.querySelector(".gallery"),g=document.querySelector(".loader"),h=document.querySelector(".load-more");document.querySelector(".loading-text");const _=new E(".gallery a");function y(r){const t=r.map(({webformatURL:a,largeImageURL:c,tags:e,likes:o,views:n,comments:w,downloads:q})=>`
    <li class="gallery__item">
      <a href="${c}">
        <img src="${a}" alt="${e}" loading="lazy" />
      </a>
      <div class="info">
        <p><b>Likes</b><br>${o}</p>
        <p><b>Views</b><br>${n}</p>
        <p><b>Comments</b><br>${w}</p>
        <p><b>Downloads</b><br>${q}</p>
      </div>
    </li>
  `).join("");p.insertAdjacentHTML("beforeend",t),_.refresh()}function $(){p.innerHTML=""}function b(){g.classList.add("is-loading")}function u(){g.classList.remove("is-loading")}function L(){h.classList.remove("hidden")}function l(){h.classList.add("hidden")}const B=document.querySelector(".form"),M=document.querySelector('input[name="search-text"]'),x=document.querySelector(".load-more"),v=15;let d="",s=1,f=0;B.addEventListener("submit",async r=>{if(r.preventDefault(),d=M.value.trim(),!d){i.warning({message:"Please enter a search term.",position:"topRight"}),u();return}s=1,$(),l(),b();try{const t=await m(d,s);if(f=t.totalHits,t.hits.length===0){i.warning({message:"No images found.",position:"topRight"});return}y(t.hits),f>s*v&&L()}catch{i.error({message:"Error fetching images.",position:"topRight"})}finally{u()}});x.addEventListener("click",async()=>{s+=1,l(),b();try{const r=await m(d,s);if(r.hits.length===0){i.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"}),l();return}y(r.hits),s*v>=f?(l(),i.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"})):L(),O()}catch{i.error({message:"Error loading more images.",position:"topRight"})}finally{u()}});function O(){const r=document.querySelector(".gallery__item");if(r){const{height:t}=r.getBoundingClientRect();window.scrollBy({top:t*2,behavior:"smooth"})}}
//# sourceMappingURL=index.js.map
