import{a as R,S as x,i}from"./assets/vendor-DfRjFiQT.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))c(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const n of o.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&c(n)}).observe(document,{childList:!0,subtree:!0});function a(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function c(e){if(e.ep)return;e.ep=!0;const o=a(e);fetch(e.href,o)}})();const _="52827134-53a8d98a66d236597fa2c26fa",$=15;async function m(r,t){return(await R.get("https://pixabay.com/api/",{params:{key:_,q:r,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:$,page:t}})).data}const g=document.querySelector(".gallery"),p=document.querySelector(".loader"),y=document.querySelector(".load-more"),b=document.querySelector(".loading-text"),B=new x(".gallery a");function L(r){const t=r.map(({webformatURL:a,largeImageURL:c,tags:e,likes:o,views:n,comments:E,downloads:P})=>`
    <li class="gallery__item">
      <a href="${c}">
        <img src="${a}" alt="${e}" loading="lazy" />
      </a>
      <div class="info">
        <p><b>Likes</b><br>${o}</p>
        <p><b>Views</b><br>${n}</p>
        <p><b>Comments</b><br>${E}</p>
        <p><b>Downloads</b><br>${P}</p>
      </div>
    </li>
  `).join("");g.insertAdjacentHTML("beforeend",t),B.refresh()}function M(){g.innerHTML=""}function v(){p.classList.add("is-loading")}function u(){p.classList.remove("is-loading")}function w(){y.classList.remove("hidden")}function l(){y.classList.add("hidden")}function q(){b.classList.remove("hidden")}function f(){b.classList.add("hidden")}const O=document.querySelector(".form"),T=document.querySelector('input[name="search-text"]'),A=document.querySelector(".load-more"),S=15;let d="",s=1,h=0;O.addEventListener("submit",async r=>{if(r.preventDefault(),d=T.value.trim(),!d){i.warning({message:"Please enter a search term.",position:"topRight"}),u(),f();return}s=1,M(),l(),v(),q();try{const t=await m(d,s);if(h=t.totalHits,t.hits.length===0){i.warning({message:"No images found.",position:"topRight"});return}L(t.hits),h>s*S?w():i.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"})}catch{i.error({message:"Error fetching images.",position:"topRight"})}finally{u(),f()}});A.addEventListener("click",async()=>{s+=1,l(),v(),q();try{const r=await m(d,s);if(r.hits.length===0){i.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"}),l();return}L(r.hits),s*S>=h?(l(),i.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"})):w(),H()}catch{i.error({message:"Error loading more images.",position:"topRight"})}finally{u(),f()}});function H(){const r=document.querySelector(".gallery__item");if(r){const{height:t}=r.getBoundingClientRect();window.scrollBy({top:t*2,behavior:"smooth"})}}
//# sourceMappingURL=index.js.map
